spring:
  application:
    name: redisson-demo

  datasource:
    url: jdbc:h2:mem:accountdb
    driverClassName: org.h2.Driver
    username: sa
    password: 123456

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

redisson:
  singleServerConfig:
    address: "redis://localhost:6379"
    timeout: 3000
    connectionPoolSize: 64
    connectionMinimumIdleSize: 24